---
# Redis StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: backend  
spec:
  serviceName: redis-service
  replicas: 3 
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/v2/shir/ofir:redis
        ports:
        - containerPort: 6379
        command:
        - /bin/sh
        - -c
        - |
          if [ "$HOSTNAME" = "redis-0" ]; then
            redis-server --requirepass yourpassword --port 6379
          else
            redis-server --slaveof redis-0.redis-service.backend.svc.cluster.local 6379 --masterauth yourpassword --port 6379
          fi
        volumeMounts:
        - name: redis-data
          mountPath: /data
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: network
                operator: In
                values:
                - private  
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi

---
# Headless Service for Redis
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: backend
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  clusterIP: None  
