version: "3.9"

services:
  web:
    build: .
    container_name: status_page_web
    environment:
      DJANGO_SETTINGS_MODULE: statuspage.settings
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: admin123
    volumes:
      - ./static:/app/static  # Static files shared with Nginx
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: status_page_nginx
    ports:
      - "8000:80"
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

  db:
    image: postgres:13
    container_name: status_page_db
    environment:
      POSTGRES_DB: statuspage
      POSTGRES_USER: statuspage
      POSTGRES_PASSWORD: abcdefgh123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statuspage"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:6
    container_name: status_page_redis
    restart: always

