site_name: Status-Page Documentation
site_dir: statuspage/project-static/docs
site_url: https://docs.status-page.dev/
repo_name: status-page/status-page
repo_url: https://github.com/status-page/status-page
edit_uri: 'edit/main/docs/'
theme:
  name: material
  custom_dir: docs/_theme/
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to Light Mode
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.chdir('statuspage/')
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "statuspage.settings")
            - django.setup()
          options:
            heading_level: 3
            members_order: source
            show_root_heading: true
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/status-page/status-page
markdown_extensions:
    - admonition
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
extra_css:
    - extra.css
nav:
    - Introduction: 'index.md'
    - Installation:
        - Install Status-Page: 'installation/index.md'
        - 1. PostgreSQL: 'installation/1-postgresql.md'
        - 2. Redis: 'installation/2-redis.md'
        - 3. Status-Page: 'installation/3-status-page.md'
        - 4. Gunicorn: 'installation/4-gunicorn.md'
        - 5. HTTP Server: 'installation/5-http-server.md'
        - Upgrading Status-Page: 'installation/upgrading.md'
    - Configuration:
        - Captcha: 'configuration/captcha.md'
    - Important Notes:
        - Captcha: 'important-notes/admin-panel.md'
    - Release Notes:
        - Overview: 'release-notes/index.md'
        - Version 2.5: 'release-notes/version-2.5.md'
        - Version 2.4: 'release-notes/version-2.4.md'
        - Version 2.3: 'release-notes/version-2.3.md'
        - Version 2.2: 'release-notes/version-2.2.md'
        - Version 2.1: 'release-notes/version-2.1.md'
        - Version 2.0: 'release-notes/version-2.0.md'
