apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: backend
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
  type: ClusterIP
